"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8o67jdq-u7p($d(a2k8jejl6^8r=c$=nb^b)bmk4sy@$&r82sg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Register jazzmin before default admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'corsheaders',
    'rest_framework',
    'django_summernote',
    # Local apps
    'portfolio',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Put CorsMiddleware at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS Configurations
CORS_ALLOW_ALL_ORIGINS = True  # For development. Change for production.
CORS_ALLOW_CREDENTIALS = True

# X-Frame options needed for Summernote admin panel editor frame rendering
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Jazzmin Admin Theme settings for premium Awwwards look
JAZZMIN_SETTINGS = {
    "site_title": "MD. RAJIBUL ISLAM SHUVO | Portfolio Admin",
    "site_header": "Shuvo Admin",
    "site_brand": "Shuvo | Developer",
    "welcome_sign": "Welcome to your Portfolio Admin Dashboard",
    "copyright": "MD. RAJIBUL ISLAM SHUVO © 2026",
    "search_model": ["portfolio.Project", "portfolio.Experience", "portfolio.BlogPost"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.user": "fas fa-user-shield",
        "portfolio.SiteSettings": "fas fa-cogs",
        "portfolio.Profile": "fas fa-user-circle",
        "portfolio.Skill": "fas fa-code",
        "portfolio.Experience": "fas fa-history",
        "portfolio.Education": "fas fa-university",
        "portfolio.Project": "fas fa-cubes",
        "portfolio.ProfessionalActivity": "fas fa-award",
        "portfolio.Certification": "fas fa-stamp",
        "portfolio.Achievement": "fas fa-trophy",
        "portfolio.Testimonial": "fas fa-quote-left",
        "portfolio.BlogPost": "fas fa-pen-nib",
        "portfolio.GalleryItem": "fas fa-image",
        "portfolio.Message": "fas fa-envelope-open-text",
        "portfolio.Statistic": "fas fa-chart-bar",
    },
    "order_with_respect_to": [
        "portfolio.SiteSettings",
        "portfolio.Profile",
        "portfolio.Statistic",
        "portfolio.Project",
        "portfolio.Experience",
        "portfolio.Education",
        "portfolio.Skill",
        "portfolio.ProfessionalActivity",
        "portfolio.Certification",
        "portfolio.Testimonial",
        "portfolio.BlogPost",
        "portfolio.Message",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "theme_cls": "theme-flatly",
    "navbar": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-dark bg-dark",
}


